

# This file was *autogenerated* from the file circular_ss.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_12 = Integer(12); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_64 = Integer(64); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8)
var('E,ν,R,h,f,w,φ_x,φ_y,k,r')
Dᵇ = E*h**_sage_const_3 /(_sage_const_12 *(_sage_const_1 -ν**_sage_const_2 ))
G = E/(_sage_const_2 *(_sage_const_1 +ν))
ξ = r/R

w = f*R**_sage_const_4 /_sage_const_64 /Dᵇ*(_sage_const_1 -ξ**_sage_const_2 )*((_sage_const_6 +_sage_const_2 *ν)/(_sage_const_1 +ν)-(_sage_const_1 +ξ**_sage_const_2 )+_sage_const_8 *(h/R)**_sage_const_2 /(_sage_const_3 *k*(_sage_const_1 -ν)))
print(latex(w))

